#!/bin/bash

echo "🚀 NAS Dashboard 快速配置"
echo "========================"
echo ""
echo "请完成以下步骤来配置您的项目："
echo ""
echo "📝 Step 1: 创建 GitHub 仓库"
echo "   1. 访问 https://github.com"
echo "   2. 点击 '+' → 'New repository'"
echo "   3. 名称: nas-dashboard"
echo "   4. 描述: 🏠 Beautiful NAS management dashboard"
echo "   5. 选择 Public"
echo "   6. 点击 'Create repository'"
echo ""
echo "🐳 Step 2: 创建 Docker Hub 仓库"
echo "   1. 访问 https://hub.docker.com"
echo "   2. 注册/登录账号"
echo "   3. 点击 'Create Repository'"
echo "   4. 名称: nas-dashboard"
echo "   5. 选择 Public"
echo "   6. 点击 'Create'"
echo ""
echo "🔐 Step 3: 获取 Docker Hub 访问令牌"
echo "   1. Docker Hub → 头像 → Account Settings"
echo "   2. Security → New Access Token"
echo "   3. 描述: GitHub Actions"
echo "   4. 权限: Read, Write, Delete"
echo "   5. 生成并复制令牌"
echo ""
echo "⚙️ Step 4: 配置 GitHub Secrets"
echo "   1. GitHub 仓库 → Settings → Secrets → Actions"
echo "   2. 添加 DOCKER_USERNAME (您的 Docker Hub 用户名)"
echo "   3. 添加 DOCKER_PASSWORD (刚才的访问令牌)"
echo ""
echo "🚀 Step 5: 推送代码"
echo "   运行以下命令 (替换 YOUR_USERNAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/nas-dashboard.git"
echo "   git push -u origin main"
echo ""
echo "✅ 完成后，GitHub Actions 将自动构建并发布到 Docker Hub！"
echo "用户可以通过以下方式安装："
echo "   docker run -d -p 3000:3000 YOUR_DOCKERHUB_USERNAME/nas-dashboard:latest"